name: Lint and Test
description: Choria Go Project Lint and Test using Ginkgo

inputs:
  ginkgo:
    description: Set to 'yes' to use Ginkgo to run tests
    default: "no"
    required: false

  run_tests:
    description: Enables running of tests
    default: "yes"
    required: false

runs:
  using: composite
  steps:
    - name: Download go dependencies
      shell: bash
      run: go mod download

    - name: Ensure well formatted files
      shell: bash
      run: |
        GO_LIST=$(go list ./...)
        $(exit $(go fmt $GO_LIST | wc -l))

    - name: Ensure tidy go mod
      shell: bash
      run: $(exit $(go mod tidy | wc -l))

    - name: Spell check
      shell: bash
      run: |
        go install github.com/client9/misspell/cmd/misspell@latest
        find . -type f -name "*.go" | xargs misspell -error -locale US -i flavour

    - name: Go vet
      shell: bash
      run: go vet $(go list ./...)

    - name: Static Check
      shell: bash
      run: |
        # specific commit needed for 1.24
        go install honnef.co/go/tools/cmd/staticcheck@0f2f29196d9a138e7beeed4e26e890cf9273f63e
        staticcheck $(go list ./...)

    - name: Go Test
      shell: bash
      run: |
        if [ "${{ inputs.run_tests }}" = "yes" ]
        then
          if [ "${{ inputs.ginkgo }}" = "yes" ]
          then
            echo "Testing using Ginkgo v1 is no longer supported"
            exit 1
          elif [ "${{ inputs.ginkgo }}" = "v2" ]
          then
            echo "Testing using Ginkgo v2"
            go install github.com/onsi/ginkgo/v2/ginkgo
            ginkgo --keep-going -vet=off --skip-package=integration -r .
          else
            go test -v -vet=off ./...
          fi
        fi
